### ISSUE TITLE
BEFORE ANYTHING ELSE: Update to current version of the template-nf

### ISSUE THREAD

**Issue by georgiesamaha** [Sydney-Informatics-Hub/SomaticShortV-nf#2]
**Time:** 0.1 day (1 hour)

**Description:** This repository needs to be updated to the more recent template structure before it can be worked on. 

**Relevant repositories**
* [sydney-informatics-hub/template-nf](https://github.com/Sydney-Informatics-Hub/template-nf)

**Activities**

- [x] Create new repository from template-nf
- [x] Name repository `Somatic-shortV-nf`
- [x] Provide feedback on template-nf as a github issue/review 
- [x] Change branch protection rules on new repository to require pull request before merging to main

**Comment by nandan75** [comment]
Thanks @georgiesamaha 

I have created the new repo [Somatic-shortV-nf](https://github.com/Sydney-Informatics-Hub/Somatic-shortV-nf) and will work with it.
