### ISSUE TITLE
Create somatic test dataset

### ISSUE THREAD

**Issue by georgiesamaha** [Sydney-Informatics-Hub/SomaticShortV-nf#3]
**Time:** 0.2 day (3 hours)
 
**Description:** Create a representative subset dataset of paired T/N fq and bams for 2 samples to ensure parallel tasks are being executed correctly, sampleIDs and files are not being confused. 

* Sample fqs named `somatic_illumina_{N,T}_R{1,2}_10k.fq.gz`. 
* Sample bams named `somatic_illumina_{N,T}_10k.bam` and indexed. 
* Subset to 10k reads for quick execution.
* Test dataset to be added to bio-test dataset repo for others to use. 

**Relevant repositories** 

* [bio-test-datasets](https://github.com/Sydney-Informatics-Hub/bio-test-datasets) 

**Activities** 

- [ ] Source suitable samples  
- [ ] Subset test fqs and bams to 10K reads, gzip fqs, index bams
- [ ] Upload to bio-test-datasets (bam directory and fastq directory)
- [ ] Rename and move current fastq files to fastq/germline to `germline-illumina_R{1,2}_10k.fq.gz` 
- [ ] Update README `contains` section with description of new datasets

**Comment by georgiesamaha** [comment]
Might source some data from nf-core/sarek?

**Comment by nandan75** [comment]
A good resource for test datasets for all nfcore pipelines 
https://github.com/nf-core/test-datasets/tree/master 


**Tiny**
https://github.com/nf-core/test-datasets/tree/sarek/testdata/recalbam

or

https://github.com/nf-core/test-datasets/blob/sarek/testdata/tsv/tiny-recal-pair.tsv

**Full sized: fastQ**
https://github.com/nf-core/test-datasets/blob/sarek/testdata/csv/HCC1395_WXS_somatic_full_test.csv

**Comment by georgiesamaha** [comment]
What about this? https://github.com/hartwigmedical/testdata

**Comment by nandan75** [comment]
- Used the fastqs from  https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html
- Used the reference on NCI Gadi at /g/data/er01/SIH-HPC-WGS/Reference and the pipeline https://github.com/Sydney-Informatics-Hub/Fastq-to-BAM to create fake T/N pair bams. The reference and the subsequent files needs to match for the Somatic-ShortV downstream analysis ; So thought it made sense to create bams using a specific reference and then use the same reference and other associated files.

- The references presently are at /scratch/er01/ndes8648/pipeline_work/nextflow/INFRA-83-Somatic-ShortV/Fastq-to-BAM_BASEDIR/Fastq-to-BAM
- I will back them up at the /g/data/er01/Bio-Test-Data - I do not have permission to make a directoy in this folder
